"""
Prometheus metrics for Dev Experience Agent.

Tracks anomaly detection, insight generation, and resolution.
"""
from prometheus_client import Counter, Histogram, Gauge

# Anomaly Detection Metrics
anomalies_detected_total = Counter(
    "crm_anomalies_detected_total",
    "Total anomalies detected by type",
    ["anomaly_type", "severity"],
)

anomaly_detection_latency = Histogram(
    "crm_anomaly_detection_latency_seconds",
    "Time to run anomaly detection",
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0),
)

# Root Cause Analysis Metrics
root_cause_analysis_total = Counter(
    "crm_root_cause_analysis_total",
    "Total root cause analyses performed",
    ["pattern_matched"],
)

root_cause_analysis_latency = Histogram(
    "crm_root_cause_analysis_latency_seconds",
    "Time to perform root cause analysis",
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0),
)

# Insight Generation Metrics
insights_generated_total = Counter(
    "crm_dev_insights_generated_total",
    "Total insights generated by severity",
    ["severity", "incident_type"],
)

insight_generation_latency = Histogram(
    "crm_insight_generation_latency_seconds",
    "Time to generate an insight",
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5),
)

insight_confidence = Histogram(
    "crm_insight_confidence",
    "Distribution of insight confidence scores",
    ["incident_type"],
    buckets=(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
)

# Insight Status Metrics
insights_active = Gauge(
    "crm_dev_insights_active",
    "Number of active (unresolved) insights",
)

insights_acknowledged = Gauge(
    "crm_dev_insights_acknowledged",
    "Number of acknowledged insights",
)

insights_resolved_total = Counter(
    "crm_dev_insights_resolved_total",
    "Total insights resolved",
)

insight_time_to_acknowledge = Histogram(
    "crm_insight_time_to_acknowledge_seconds",
    "Time from insight creation to acknowledgement",
    buckets=(60, 300, 900, 1800, 3600, 7200, 14400),  # 1m, 5m, 15m, 30m, 1h, 2h, 4h
)

insight_time_to_resolve = Histogram(
    "crm_insight_time_to_resolve_seconds",
    "Time from insight creation to resolution",
    buckets=(300, 900, 1800, 3600, 7200, 14400, 28800),  # 5m, 15m, 30m, 1h, 2h, 4h, 8h
)

# Suggestion Metrics
suggestions_generated_total = Counter(
    "crm_suggestions_generated_total",
    "Total suggestions generated by category",
    ["category", "requires_approval"],
)
